# Generated by Django 3.1.7 on 2021-03-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShppingAdress',
            new_name='ShippingAdress',
        ),
    ]
